# Generated by Django 2.0.2 on 2018-02-03 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, unique=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('order_number', models.CharField(max_length=200)),
                ('file_path', models.CharField(blank=True, default='', max_length=2048)),
                ('details', models.TextField(blank=True, default='')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de commande')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'ajout")),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('RUB', 'RUB')], default='EUR', max_length=3)),
                ('net_paid', models.DecimalField(decimal_places=5, max_digits=14)),
                ('included_vat', models.DecimalField(decimal_places=5, max_digits=13)),
                ('currency_to_EUR_rate', models.DecimalField(decimal_places=10, default=1, max_digits=19)),
                ('vat_rate', models.DecimalField(decimal_places=5, default=0.2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2048)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=14)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase')),
            ],
        ),
    ]
