# Generated by Django 2.0.2 on 2018-02-03 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=200, unique=True)),
                ('nom_fournisseur', models.CharField(max_length=200)),
                ('numero_commande', models.CharField(max_length=200)),
                ('chemin_fichier', models.CharField(blank=True, default='', max_length=2048)),
                ('autres_informations', models.TextField(blank=True, default='')),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de commande')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'ajout")),
                ('devise', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('RUB', 'RUB')], default='EUR', max_length=3)),
                ('net_paye', models.DecimalField(decimal_places=5, max_digits=14)),
                ('dont_tva', models.DecimalField(decimal_places=5, max_digits=13)),
                ('taux_de_change', models.DecimalField(decimal_places=10, default=1, max_digits=19)),
                ('taux_tva', models.DecimalField(decimal_places=5, default=0.2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='LigneArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2048)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=6)),
                ('prix_unitaire', models.DecimalField(decimal_places=5, max_digits=14)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Achat')),
            ],
        ),
    ]
