# Generated by Django 2.0.2 on 2018-02-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
