# Generated by Django 2.0.2 on 2018-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20180203_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
