# Generated by Django 2.0.2 on 2018-02-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_purchase_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='details',
            new_name='description',
        ),
    ]
